version: "3"
services:
  nginx:
    depends_on:
      - backend
      - frontend
    image: "nginx:latest"
    container_name: "nginx"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:8080"
    networks:
      - xmas-network

  backend:
    build: "."
    container_name: "xhat-backend"
    expose:
      - "8000"
    networks:
      - "xmas-network"

  frontend:
    build: "./website"
    container_name: "xhat-frontend"
    expose:
      - "3000"
    networks:
      - xmas-network

networks:
  xmas-network:
