version: "3"
services:
  nginx:
    depends_on:
      - frontend
      - backend
    image: "nginx:latest"
    container_name: "nginx"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:8080"
    networks:
      - xmas-network

  frontend:
    image: "flandiayingman/xmas-hat-gen-frontend"
    container_name: "xhat-frontend"
    expose:
      - "3000"
    networks:
      - xmas-network

  backend:
    image: "flandiayingman/xmas-hat-gen-backend"
    container_name: "xhat-backend"
    expose:
      - "8000"
    networks:
      - "xmas-network"

networks:
  xmas-network:
